### PR TITLE
fix: bucket list for_each_ranged

### LINKED ISSUE #564: Query objects bug
When querying nested objects with a small limit, I get strange results with either missing objects or a `nextKey` that makes no sense. For example...

Query the root of the bucket:
```
recall bu query --address 0xFf000000000000000000000000000000000000c3 --prefix "" --delimiter "/"
{
  "objects": [
    {
      "key": "small",
      "value": {
        "hash": "5caiefwpdgkaafczarx6ofb42mmj2mmtc6pqlkvwj5un45i2goea",
        "size": 2039
      }
    },
    {
      "key": "another",
      "value": {
        "hash": "humk3nwgl72rrjubkxysaqrhzw7f4kwcvr2rsrxdhtdtrhknlygq",
        "size": 4700,
        "metadata": {
          "size": "4700",
          "type": "text/plain"
        }
      }
    }
  ],
  "common_prefixes": [
    "nested/"
  ],
  "next_key": null
}
```
It contains two objects and a nested prefix.

Query that nested prefix with no limit:
```
> recall bu query --address 0xFf000000000000000000000000000000000000c3 --prefix "nested/" --delimiter "/" --limit 0
{
  "objects": [
    {
      "key": "nested/foo",
      "value": {
        "hash": "xpofvsqpk3v6jmnq2kn6lr2ioiuuffvqolqb3llcbuzpypjbpicq",
        "size": 561,
        "metadata": {
          "size": "561",
          "type": "text/calendar"
        }
      }
    }
  ],
  "common_prefixes": [],
  "next_key": null
}
```
This looks correct. It lists the single object contained in there.

Same query, but with a limit of 1. This should return the same result, but:
```
> recall bu query --address 0xFf000000000000000000000000000000000000c3 --prefix "nested/" --delimiter "/" --limit 1
{
  "objects": [],
  "common_prefixes": [],
  "next_key": "another"
}
```
I get no objects and a `nextKey` which is the key of one of the object is the root of the bucket. Weird.

Limit of 2 produces also weird results:
```
> recall bu query --address 0xFf000000000000000000000000000000000000c3 --prefix "nested/" --delimiter "/" --limit 2
{
  "objects": [],
  "common_prefixes": [],
  "next_key": "nested/foo"
}
```

Limit 3 works fine:
```
> recall bu query --address 0xFf000000000000000000000000000000000000c3 --prefix "nested/" --delimiter "/" --limit 3
{
  "objects": [
    {
      "key": "nested/foo",
      "value": {
        "hash": "xpofvsqpk3v6jmnq2kn6lr2ioiuuffvqolqb3llcbuzpypjbpicq",
        "size": 561,
        "metadata": {
          "size": "561",
          "type": "text/calendar"
        }
      }
    }
  ],
  "common_prefixes": [],
  "next_key": null
}
```

### PR DESCRIPTION
**Pull request by brunocalza**
# Summary

Closes #564 

- Changes the bucket state to use the `hamt` from `recall_ipld`
- Implements a custom `for_each_ranged` that allows skipping elements that don't match a prefix

# Details

The easiest way to understand the behavior is to upload two objects (`hello` and `test/hello`). I've done that in `testnet`. You can try. Querying `testnet`,

```
recall bu query -a 0xff000000000000000000000000000000000000fd --prefix test --limit 1
{
  "objects": [],
  "common_prefixes": [],
  "next_key": "test/hello"
}
```

I queried by prefix with limit 1, and it returned nothing, although we know there's something there. We can only get that element by doing another call. 

With this PR, we'll return the correct element in just one call because we skip the element (`hello`) that does not match the prefix.

There's still one thing that could be strange

```
recall bu query -a 0xff000000000000000000000000000000000000fd --limit 1              
{
  "objects": [
    {
      "key": "hello",
      "value": {
        "hash": "z5oyjijptdwp3jnxqi3m7nmepzzdjqc5yxpperxfk4xnohnwaguq",
        "size": 6,
        "expiry": 1372597,
        "metadata": {
          "content-type": "text/plain"
        }
      }
    }
  ],
  "common_prefixes": [],
  "next_key": "test/hello"
}
```

I queried without prefix. It returned the correct element, but it also returned the `next_key`.  It should have been `null`, because we know there's nothing there. That's because "test/hello" comes next in the `hamt`. TBH I don't know if there's an easy solution to this. 

In short, this whole issue arises because we're not really doing an indexed search on the prefix, we're querying the hamt and then seeing if the prefix matches or not. 

cc @asutula

### CODE REVIEW

File: recall/ipld/src/hamt/core.rs [hunk 1]
```diff
@@ -198,9 +210,9 @@ where
         // Note the result type of F uses ActorError.
         // The implementation will extract and propagate any ActorError
         // wrapped in a hamt::Error::Dynamic.
-        F: FnMut(K, &V) -> Result<(), ActorError>,
+        F: FnMut(K, &V) -> Result<bool, ActorError>,
```
Comment (brunocalza) [inline recall/ipld/src/hamt/core.rs:213]: **Part 1 of the fix:** add a flag

So, `F` is called on every element that is being iterated inside `for_each_ranged`. Here, we add a flag to `F`, so that `F` can indicate to `for_each_ranged` if that element should be considered or not in the `limit` count.

File: recall/ipld/src/hamt/core.rs [hunk 2]
```diff
@@ -219,6 +231,42 @@ where
         }
     }
 
+    fn inner_for_each_ranged<F>(
```
Comment (brunocalza) [inline recall/ipld/src/hamt/core.rs:234]: **Part II of the fix**: use that flag to skip (`continue`) the element that didn't match the prefix

File: recall/ipld/src/hamt/core.rs [hunk 3]
```diff
@@ -219,6 +231,42 @@ where
...
+        let limit = max.unwrap_or(usize::MAX);
+        loop {
+            if traversed >= limit {
+                break
+            }
+
+            match iter.next() {
+                Some(res) => {
+                    let (k, v) = res?;
+                    if !(f)(k, v)? {
```
Comment (brunocalza) [inline recall/ipld/src/hamt/core.rs:258]: if the flag is `false`, we go to the next element and don't increase `traversed`. Take a look at the [original implementation](https://github.com/filecoin-project/ref-fvm/blob/master/ipld/hamt/src/hamt.rs#L424-L449), see how the use of the flag allows us to skip elements without increasing `traversed`

File: fendermint/actors/bucket/src/state.rs [hunk 4]
```diff
@@ -701,4 +705,61 @@ mod tests {
         let result = result.unwrap();
         assert_eq!(result.0.len(), 1);
     }
+
+    #[test]
+    fn test_list_with_prefix_and_without_and_limit() {
```
Comment (brunocalza) [inline fendermint/actors/bucket/src/state.rs:710]: This test somehow illustrates the problem. In `main`, it fails, because one of the `list` results in `0` elements

File: fendermint/actors/blobs/src/state.rs [hunk 5]
```diff
@@ -622,7 +622,7 @@ impl State {
                 account.last_debit_epoch = current_epoch;
                 debug!("debited {} credits from {}", debit_credits, address);
                 writer.set(&address, account)?;
-                Ok(())
+                Ok(true)
```
Comment (brunocalza) [inline fendermint/actors/blobs/src/state.rs:625]: This is just because we changed the signature, and now we must pass a flag

**Comment by asutula** [comment]
> I queried without prefix. It returned the correct element, but it also returned the next_key. It should have been null,...
This actually doesn't look wrong to me, but maybe it's right for the wrong reasons... My understanding/experience is that a page of data includes objects and common prefixes, the sum of both being the page size. So, if you say `--limit 1` on a bucket that has one object and one prefix in the root, I'd expect the page to have just to object, and the next page to contain the prefix.

File: fendermint/actors/bucket/src/state.rs [hunk 6]
```diff
@@ -215,7 +190,58 @@ impl State {
         })?;
 
         let common_prefixes = common_prefixes.into_iter().collect();
-        Ok((common_prefixes, next_key))
+        Ok((common_prefixes, next_key.map(|key| key.0)))
+    }
+}
+
+#[derive(Debug, PartialEq)]
+pub struct ObjectKey(pub BytesKey);
```
Comment (brunocalza) [inline fendermint/actors/bucket/src/state.rs:198]: This is a bit annoying, but I had to do it. `BytesKey` does not implement `Display` which is needed, and we can't implement `Display` on `BytesKey` because of the orphan rule

File: recall/ipld/src/hamt.rs
[the remark this answers is not in the document]
Comment (brunocalza) [reply recall/ipld/src/hamt.rs:1]: Added another commit for this change

**Review by sanderpick — APPROVED** [review]
sweet. lgtm!
