### PR TITLE
fix: download of key with different delimiter

### LINKED ISSUE #596: Fix objects API for getting objects
I've noticed some problems with the way that the objects API supports download object data:

1. It currently relies on a REST style URL path to represent the path to the object to download. The Recall protocol supports object keys that can't be represented by a REST style URL path. For example, the only types of objects that can be fetched from the objects API endpoint are ones that use `/` as a delimiter character, and that don't have any repeated delimiter characters like `///`. The protocol supports any delimiter character and repeated delimited characters.
2. URL encoded characters in object paths don't decode and resolve to an object. This results in a 404 not found error. For example, a path of `foo?bar?baz.txt` does not resolve to an object when fetching it from the object API: Both `https://objects.testnet.recall.chain.love/v1/objects/0xFF000000000000000000000000000000000000b5/foo?bar?baz.txt` and `https://objects.testnet.recall.chain.love/v1/objects/0xFF000000000000000000000000000000000000b5/foo%3Fbar%3Fbaz.txt` return 404 not found.

### PR DESCRIPTION
**Pull request by brunocalza**
# Summary 

Closes #596 

We must assume that the object key can be url-encoded, so we must try decoding the key.

Note:
- SDKs must be changed to make sure keys are url-encoded

cc @dtbuchholz in case there is something in docs that must be changed

### CODE REVIEW

File: fendermint/app/src/cmd/objects.rs [hunk 1]
```diff
@@ -94,8 +93,7 @@ cmd! {
                 .and(with_max_size(settings.max_object_size))
                 .and_then(handle_object_upload);
 
-                let objects_download = warp::path!("v1" / "objects" / String / ..)
-                .and(warp::path::tail())
+                let objects_download = warp::path!("v1" / "objects" / String / String )
```
Comment (brunocalza) [inline fendermint/app/src/cmd/objects.rs:96]: The thing is that `/ ..` matches the tail of an HTTP path. If you have `foo?bar?baz.txt` as the object key, it will match only `foo` because the path ends at `?` each is a query string identifier. By switching to  `/ String` we are able to capture everything as long as it's URL-encoded.

File: fendermint/app/src/cmd/objects.rs [hunk 2]
```diff
@@ -593,7 +591,15 @@ async fn handle_object_download<F: QueryClient + Send + Sync>(
     let height = height_query
         .height
         .unwrap_or(FvmQueryHeight::Committed.into());
-    let path = tail.as_str();
+
+    let path = urlencoding::decode(tail.as_str())
```
Comment (brunocalza) [inline fendermint/app/src/cmd/objects.rs:595]: we must decode now

File: fendermint/app/src/cmd/objects.rs (hunk 1 above)
Comment (asutula) [reply fendermint/app/src/cmd/objects.rs:96]: Hmm, I guess I'm surprised that there is no way to get "all the remaining path" whether it is URL encoded or not. Some "greedy" version of `String`. That would allow us to use pretty paths like `foo/bar/baz` or the URL encoded version of it `foo%2Fbar%2Fbaz`.

Comment (avichalp) [reply fendermint/app/src/cmd/objects.rs:96]: how about restricting arbitrary key names at the protocol level? only allow certain characters in the key name and validate that when creating new objects

Comment (dtbuchholz) [reply fendermint/app/src/cmd/objects.rs:96]: here's what [s3 enforces](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html):

Screenshot 2025-04-07 at 3 45 06 PM

Comment (brunocalza) [reply fendermint/app/src/cmd/objects.rs]: > mm, I guess I'm surprised that there is no way to get "all the remaining path" whether it is URL encoded or not. Some "greedy" version of `String`. That would allow us to use pretty paths like `foo/bar/baz` or the URL encoded version of it `foo%2Fbar%2Fbaz`.

yeah, i've double checked and looks like using

```
let objects_download = warp::path!("v1" / "objects" / String / ..)
                .and(warp::path::tail())
```

works as you say. I thought I had tested that and couldn't get it to work with URL-encoded values, but anyways. I guess we're good, then. We can have both `foo/bar/baz` and `foo%2Fbar%2Fbaz`. And just to clarify, for other delimiters, it must be URL-encoded (e.g. `?`, `#` have special meanings in HTTP URLs). However, SDKs should always encode the URLs because you can't know what delimiter the user is using. Does it make sense?

I made this change in a new commit


> how about restricting arbitrary key names at the protocol level? only allow certain characters in the key name and validate that when creating new objects

i don't think restricting helps actually. the issue was more like if there was a way to support both `foo/bar/baz` and `foo%2Fbar%2Fbaz` with one route matcher

File: fendermint/app/src/cmd/objects.rs [hunk 3]
```diff
@@ -94,7 +93,7 @@ cmd! {
                 .and(with_max_size(settings.max_object_size))
                 .and_then(handle_object_upload);
 
-                let objects_download = warp::path!("v1" / "objects" / String / ..)
+                let objects_download = warp::path!("v1" / "objects" / String / .. )
```
Comment (avichalp) [inline fendermint/app/src/cmd/objects.rs:96]: how does adding a whitespace helps here? 🧐

File: fendermint/app/src/cmd/objects.rs (hunk 1 above)
Comment (asutula) [reply fendermint/app/src/cmd/objects.rs]: Nice @brunocalza. I'm glad that works. Yes, if you don't URL encode on the client side, you may get 404 not found. I think that is reasonable and expected. It's nice that for buckets that use "simple" keys with just letters and single `/` as delimiters, they can still have nice looking URLs if wanted/needed.

**Review by asutula — APPROVED** [review]
