### PR TITLE
fix: blob size validation

### LINKED ISSUE #458: Blob size vulnerability
In the current architecture, where a user first stages data in a validator (either using Iroh's reverse upload or directly) it is possible that user uploads a big blob lets say 1GB. But it overrides the `size` param in the SDK to a smaller value eg: 1MB. In this case, the user will be only charged for storing 1MB where as the validators will be forced to store 1GB

### PR DESCRIPTION
**Pull request by avichalp**
## Summary

This PR addresses issue #458 where malicious users could upload large blobs while declaring smaller sizes in the SDK, resulting in validators storing more data than users are charged for.

## Problem

In the current implementation, users first stage data in a validator (either using Iroh's reverse upload or directly). Without proper validation, a user could:
1. Upload a large blob (e.g., 1GB) 
2. But override the `size` parameter in the SDK to a smaller value (e.g., 1MB)
3. Result: User is charged for storing only 1MB while validators are forced to store the full 1GB

## Solution

The PR implements size validation at multiple checkpoints throughout the blob lifecycle:

1. **Size Verification During Set Pending**: Added a validation check in `set_blob_pending` that verifies the blob's actual size matches the claimed size before changing status to pending
   ```rust
   if blob.size != size {
       return Err(ActorError::assertion_failed(format!(
           "blob {} size mismatch (expected: {}; actual: {})",
           hash, size, blob.size
       )));
   }
   ```

2. **Size Validation During Download**: Added validation in the Iroh resolver to ensure downloaded blob size matches the expected size
   ```rust
   if res.local_size + res.downloaded_size != size {
       return Err(anyhow!(
           "downloaded blob size {} does not match expected size {}",
           res.local_size + res.downloaded_size,
           size
       ));
   }
   ```

3. **Size Information Propagation**: Modified relevant data structures to carry size information throughout the resolution process:
   - Added size to `BlobRequest`, `PendingBlob`, and `FinalizedBlob` structures
   - Updated `BlobPoolItem` to include size parameter
   - Modified Iroh resolver interfaces to include size validation

## Key Changes

1. **Data Structure Updates**:
   - Modified `BlobRequest` to include blob size: `(Hash, u64, HashSet<(Address, SubscriptionId, PublicKey)>)`
   - Added size field to `FinalizedBlob` and `PendingBlob` structures
   - Updated `BlobPoolItem` to include size information

2. **Function Modifications**:
   - Updated `get_added_blobs` and `get_pending_blobs` to return blob size
   - Modified `set_blob_pending` to accept and validate size parameter
   - Updated Iroh resolver to verify downloaded sizes

3. **Validation Points**:
   - Blob actor validates size matches during pending status changes
   - Iroh download process validates actual downloaded size matches claimed size

This fix ensures users cannot exploit the system by misrepresenting blob sizes, protecting validators from storing more data than they're compensated for.

Resolves #458

### CODE REVIEW

File: fendermint/actors/blobs/src/state.rs [hunk 1]
```diff
@@ -1038,30 +1042,40 @@ impl State {
...
+    pub fn get_added_blobs<BS: Blockstore>(&self, store: &BS, size: u32) -> BlobSourcesResult {
+        let blobs = self.blobs.hamt(store)?;
+        self.added
+            .take_page(store, size)?
+            .into_iter()
+            .map(|(hash, sources)| {
+                let blob = blobs
+                    .get(&hash)?
+                    .ok_or_else(|| ActorError::not_found(format!("blob {} not found", hash)))?;
+                Ok((hash, blob.size, sources))
```
Comment (avichalp) [inline fendermint/actors/blobs/src/state.rs:1054]: Gets the size of the pending blob and return it to Fendermint

File: fendermint/actors/blobs/src/state.rs [hunk 2]
```diff
@@ -1038,30 +1042,40 @@ impl State {
...
+    pub fn get_pending_blobs<BS: Blockstore>(&self, store: &BS, size: u32) -> BlobSourcesResult {
+        let blobs = self.blobs.hamt(store)?;
+        self.pending
+            .take_page(store, size)?
+            .into_iter()
+            .map(|(hash, sources)| {
+                let blob = blobs
+                    .get(&hash)?
+                    .ok_or_else(|| ActorError::not_found(format!("blob {} not found", hash)))?;
+                Ok((hash, blob.size, sources))
```
Comment (avichalp) [inline fendermint/actors/blobs/src/state.rs:1068]: Returns the size of pending blobs to Fendermint.

File: fendermint/vm/interpreter/src/chain.rs [hunk 3]
```diff
@@ -887,6 +893,7 @@ where
                         env.blob_pool.add(BlobPoolItem {
                             subscriber: blob.subscriber,
                             hash: blob.hash,
+                            size: blob.size,
```
Comment (avichalp) [inline fendermint/vm/interpreter/src/chain.rs:896]: Added `size` in the pool item so it can be checked against the download blob.

File: fendermint/vm/message/src/ipc.rs [hunk 4]
```diff
@@ -128,6 +128,8 @@ pub struct FinalizedBlob {
     pub subscriber: Address,
     /// The blake3 hash of the blob.
     pub hash: Hash,
+    /// The size of the blob.
+    pub size: u64,
```
Comment (avichalp) [inline fendermint/vm/message/src/ipc.rs:132]: `FinalizedBlob` needs to have size to construct `BlobPoolItem` again so it can be removed from the pool.

**Comment by avichalp** [comment]
## Suggested PR Description

## Summary

This PR addresses a critical security vulnerability (issue #458) where malicious users could upload large blobs while declaring smaller sizes in the SDK, resulting in validators storing more data than users are charged for.

## Problem

In the current architecture, users first stage data in a validator (either using Iroh's reverse upload or directly). Without proper validation, a user could:
1. Upload a large blob (e.g., 1GB) 
2. But override the `size` parameter in the SDK to a smaller value (e.g., 1MB)
3. Result: User is charged for storing only 1MB while validators are forced to store the full 1GB

## Solution

The PR implements size validation at multiple checkpoints throughout the blob lifecycle:

1. **Size Verification During Set Pending**: Added a validation check in `set_blob_pending` that verifies the blob's actual size matches the claimed size before changing status to pending
   ```rust
   if blob.size != size {
       return Err(ActorError::assertion_failed(format!(
           "blob {} size mismatch (expected: {}; actual: {})",
           hash, size, blob.size
       )));
   }
   ```

2. **Size Validation During Download**: Added validation in the Iroh resolver to ensure downloaded blob size matches the expected size
   ```rust
   if res.local_size + res.downloaded_size != size {
       return Err(anyhow!(
           "downloaded blob size {} does not match expected size {}",
           res.local_size + res.downloaded_size,
           size
       ));
   }
   ```

3. **Size Information Propagation**: Modified relevant data structures to carry size information throughout the resolution process:
   - Added size to `BlobRequest`, `PendingBlob`, and `FinalizedBlob` structures
   - Updated `BlobPoolItem` to include size parameter
   - Modified Iroh resolver interfaces to include size validation

## Key Changes

1. **Data Structure Updates**:
   - Modified `BlobRequest` to include blob size: `(Hash, u64, HashSet<(Address, SubscriptionId, PublicKey)>)`
   - Added size field to `FinalizedBlob` and `PendingBlob` structures
   - Updated `BlobPoolItem` to include size information

2. **Function Modifications**:
   - Updated `get_added_blobs` and `get_pending_blobs` to return blob size
   - Modified `set_blob_pending` to accept and validate size parameter
   - Updated Iroh resolver to verify downloaded sizes

3. **Validation Points**:
   - Blob actor validates size matches during pending status changes
   - Iroh download process validates actual downloaded size matches claimed size

This fix ensures users cannot exploit the system by misrepresenting blob sizes, protecting validators from storing more data than they're compensated for.

Resolves #458

File: fendermint/actors/blobs/src/state.rs [hunk 5]
```diff
@@ -25,6 +25,9 @@ use log::{debug, warn};
 use num_traits::{ToPrimitive, Zero};
 use recall_ipld::hamt::{BytesKey, MapKey};
 
+type BlobSourcesResult =
+    anyhow::Result<Vec<(Hash, u64, HashSet<(Address, SubscriptionId, PublicKey)>)>, ActorError>;
```
Comment (sanderpick) [inline fendermint/actors/blobs/src/state.rs:29]: at some point we should make these giant types into structs

File: rust-toolchain.toml [hunk 6]
```diff
@@ -1,4 +1,4 @@
 [toolchain]
-channel = "1.81.0"
+channel = "1.82.0"
```
Comment (sanderpick) [inline rust-toolchain.toml:2]: do we need to do this on this PR? I think CI will need to be changed as well... esp. the docker build and publish

**Review by sanderpick — APPROVED** [review]
very nice! big improvement. i left one question about changing the toolchain version

File: fendermint/actors/blobs/src/state.rs (hunk 5 above)
Comment (avichalp) [reply fendermint/actors/blobs/src/state.rs:29]: https://github.com/recallnet/ipc/issues/571

File: rust-toolchain.toml (hunk 6 above)
Comment (avichalp) [reply rust-toolchain.toml:2]: i will revert this for now
